const MIN_STRING_NAME = 2;
const MAX_STRING_NAME = 50;
const MIN_TEXT_NAME = 2;
const MAX_TEXT_NAME = 2;

module.exports = {
  MIN_STRING_NAME,
  MAX_STRING_NAME,
  MIN_TEXT_NAME,
  MAX_TEXT_NAME,
};
